# -*- coding: utf-8 -*-
"""feature_engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7Wp_5LqaJxedZIiycbtB2yv77ausVlX
"""

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def calculate_similarity(cv_vectors, jd_vectors):
    """Menghitung Cosine Similarity antara matriks CV dan JD."""
    similarity_scores = []
    for i in range(cv_vectors.shape[0]):
        similarity = cosine_similarity(cv_vectors[i], jd_vectors[i])[0][0]
        similarity_scores.append(similarity)
    return similarity_scores

def calculate_skill_match(cv_text, jd_text, skills_list):
    """Menghitung persentase kecocokan skill spesifik."""
    cv_text = str(cv_text).lower()
    jd_text = str(jd_text).lower()

    cv_skills = [skill for skill in skills_list if skill in cv_text]
    jd_skills = [skill for skill in skills_list if skill in jd_text]

    if len(jd_skills) == 0:
        return 0.0

    matched_skills = set(cv_skills).intersection(set(jd_skills))
    return len(matched_skills) / len(jd_skills)

def detect_experience(text):
    """Mendeteksi level pengalaman dari teks Job Description."""
    text = str(text).lower()
    if 'senior' in text:
        return 3
    elif 'mid' in text:
        return 2
    elif 'junior' in text:
        return 1
    else:
        return 0

def process_features(df, vectorizer, skills_list):
    """Fungsi utama untuk menjalankan seluruh Feature Engineering."""
    # 1. Cosine Similarity
    cv_vectors = vectorizer.transform(df['cv_clean'])
    jd_vectors = vectorizer.transform(df['job_clean'])
    df['similarity_score'] = calculate_similarity(cv_vectors, jd_vectors)

    # 2. Skill Match Score
    df['skill_match_score'] = df.apply(
        lambda x: calculate_skill_match(x['cv_clean'], x['job_clean'], skills_list), axis=1
    )

    # 3. Experience Level Encoding
    df['experience_encoded'] = df['job_clean'].apply(detect_experience)

    return df